apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: vote-cicd-triggertemplate
spec:
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      name: pipelinerun-$(uid)
    spec:
      pipelineRef:
        name: hello-goodbye
